
theme: jekyll-theme-cayman
> title: > The Framing of Environmental Issues in Chinese Media
> # description: > Discussion of Climate Change &#8212; A Comparative Study //  <b>« Green mountains and clear water are equal to mountains of gold and silver. »</b><i>&#12316;Xi Jinping</i>

menu: [
{'name': 'Overview', 'pagename': 'index'},
{'name': 'I. Sources and Methodology', 'pagename': 'page6'},
{'name': 'II. Media and Government', 'pagename': 'page1'},
{'name': 'III. Prototypes: South China Morning Post vs. China Daily', 'pagename': 'page2'},
{'name': 'IV. Topic Modeling', 'pagename': 'page3'},
{'name': 'V. Contingency Matrix', 'pagename': 'page4'},
{'name': 'VI. Network Analysis', 'pagename': 'page5'},
{'name': 'VII. Criticality Index', 'pagename': 'page7'},
{'name': 'Contact & Comments', 'pagename': 'page8'},
]
